
package com.tb.service.sjtb.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProvService", targetNamespace = "http://services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProvService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadCaseCNInfo", targetNamespace = "http://services/", className = "com.tb.service.sjtb.wsdl.UploadCaseCNInfo")
    @ResponseWrapper(localName = "uploadCaseCNInfoResponse", targetNamespace = "http://services/", className = "com.tb.service.sjtb.wsdl.UploadCaseCNInfoResponse")
    @Action(input = "http://services/ProvService/uploadCaseCNInfoRequest", output = "http://services/ProvService/uploadCaseCNInfoResponse")
    public String uploadCaseCNInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadWeighInfo", targetNamespace = "http://services/", className = "com.tb.service.sjtb.wsdl.UploadWeighInfo")
    @ResponseWrapper(localName = "uploadWeighInfoResponse", targetNamespace = "http://services/", className = "com.tb.service.sjtb.wsdl.UploadWeighInfoResponse")
    @Action(input = "http://services/ProvService/uploadWeighInfoRequest", output = "http://services/ProvService/uploadWeighInfoResponse")
    public String uploadWeighInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadWeighPicInfo", targetNamespace = "http://services/", className = "com.tb.service.sjtb.wsdl.UploadWeighPicInfo")
    @ResponseWrapper(localName = "uploadWeighPicInfoResponse", targetNamespace = "http://services/", className = "com.tb.service.sjtb.wsdl.UploadWeighPicInfoResponse")
    @Action(input = "http://services/ProvService/uploadWeighPicInfoRequest", output = "http://services/ProvService/uploadWeighPicInfoResponse")
    public String uploadWeighPicInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadRoadCaseInfo", targetNamespace = "http://services/", className = "com.tb.service.sjtb.wsdl.UploadRoadCaseInfo")
    @ResponseWrapper(localName = "uploadRoadCaseInfoResponse", targetNamespace = "http://services/", className = "com.tb.service.sjtb.wsdl.UploadRoadCaseInfoResponse")
    @Action(input = "http://services/ProvService/uploadRoadCaseInfoRequest", output = "http://services/ProvService/uploadRoadCaseInfoResponse")
    public String uploadRoadCaseInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "upload1And4CaseInfo", targetNamespace = "http://services/", className = "com.tb.service.sjtb.wsdl.Upload1And4CaseInfo")
    @ResponseWrapper(localName = "upload1And4CaseInfoResponse", targetNamespace = "http://services/", className = "com.tb.service.sjtb.wsdl.Upload1And4CaseInfoResponse")
    @Action(input = "http://services/ProvService/upload1And4CaseInfoRequest", output = "http://services/ProvService/upload1And4CaseInfoResponse")
    public String upload1And4CaseInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "upload1And4CaseRelatedInfo", targetNamespace = "http://services/", className = "com.tb.service.sjtb.wsdl.Upload1And4CaseRelatedInfo")
    @ResponseWrapper(localName = "upload1And4CaseRelatedInfoResponse", targetNamespace = "http://services/", className = "com.tb.service.sjtb.wsdl.Upload1And4CaseRelatedInfoResponse")
    @Action(input = "http://services/ProvService/upload1And4CaseRelatedInfoRequest", output = "http://services/ProvService/upload1And4CaseRelatedInfoResponse")
    public String upload1And4CaseRelatedInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
