
package com.tb.service.sjtb.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProvServiceService", targetNamespace = "http://services/", wsdlLocation = "http://10.228.2.37:8080/ZCProject_war/ProvService?wsdl")
public class ProvServiceService
    extends Service
{

    private final static URL PROVSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PROVSERVICESERVICE_EXCEPTION;
    private final static QName PROVSERVICESERVICE_QNAME = new QName("http://services/", "ProvServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.228.2.37:8080/ZCProject_war/ProvService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROVSERVICESERVICE_WSDL_LOCATION = url;
        PROVSERVICESERVICE_EXCEPTION = e;
    }

    public ProvServiceService() {
        super(__getWsdlLocation(), PROVSERVICESERVICE_QNAME);
    }

    public ProvServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROVSERVICESERVICE_QNAME, features);
    }

    public ProvServiceService(URL wsdlLocation) {
        super(wsdlLocation, PROVSERVICESERVICE_QNAME);
    }

    public ProvServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROVSERVICESERVICE_QNAME, features);
    }

    public ProvServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProvServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProvService
     */
    @WebEndpoint(name = "ProvServicePort")
    public ProvService getProvServicePort() {
        return super.getPort(new QName("http://services/", "ProvServicePort"), ProvService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProvService
     */
    @WebEndpoint(name = "ProvServicePort")
    public ProvService getProvServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services/", "ProvServicePort"), ProvService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROVSERVICESERVICE_EXCEPTION!= null) {
            throw PROVSERVICESERVICE_EXCEPTION;
        }
        return PROVSERVICESERVICE_WSDL_LOCATION;
    }

}
